config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  resources :tipo_servicos
  resources :unidades
  resources :insumos
  resources :composicaos
  resources :servicos
  resources :obras
  resources :users
  resources :orcamentos

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get    'sign_out'  => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'


  root 'sessions#new'
end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
  	filterrific(
 		default_filter_params: { sorted_by: 'descricao_desc' },
  		available_filters: [
  			:sorted_by,
    		:search_query
  		]
	)

	scope :search_query, lambda { |query|
  		where("descricao LIKE ?", "%#{query}%")  
  	}

  	scope :sorted_by, lambda { |sort_option|
	  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
	  case sort_option.to_s
	  when /^descricao/
	    order("LOWER(unidades.descricao) #{ direction }")
    when /^sigla/
      order("LOWER(unidades.sigla) #{ direction }")
	  else
	    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
	  end
  	}

  	def self.options_for_sorted_by 
  		[
      		['Descrição (a-z)', 'descricao_asc'],
          ['Descrição (z-a)', 'descricao_desc'],
          ['Sigla (a-z)', 'sigla_asc'],
          ['Sigla (z-a)', 'sigla_desc']
    	]
  	end
	
	def self.options_for_select
  		order('LOWER(sigla)').map { |e| [e.sigla, e.id] }
  	end
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  
  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all

    @filterrific = initialize_filterrific(
      Unidade,
      params[:filterrific]
    ) or return

    @filterrific.select_options = {
      sorted_by: Unidade.options_for_sorted_by
    }

    @unidades = @filterrific.find.page(params[:page]).per(20)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1
  # PATCH/PUT /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade.destroy
    respond_to do |format|
      format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidade_params
      params.require(:unidade).permit(:descricao, :sigla, :qtd_dimensao, :monetaria)
    end
end

app/helpers/unidade_helper.rb
module UnidadeHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= form_for(unidade) do |f| %>
  <% if unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unidade.errors.count, "error") %> prohibited this unidade from being saved:</h2>

      <ul>
      <% unidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="field">
    <%= f.label :sigla %>
    <%= f.text_field :sigla %>
  </div>

  <div class="field">
    <%= f.label :qtd_dimensao %>
    <%= f.number_field :qtd_dimensao %>
  </div>

  <div class="field">
    <%= f.label :monetaria %>
    <%= f.check_box :monetaria %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unidades/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info unidades %>
  </div>

<table border="1">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Descricao</th>
      <th>Sigla</th>
      <th>Qtd dimensao</th>
      <th>Monetaria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.id %></td>
        <td><%= unidade.descricao %></td>
        <td><%= unidade.sigla %></td>
        <td><%= unidade.qtd_dimensao %></td>
        <td><%= unidade.monetaria %></td>
        <td><%= link_to 'Show', unidade %></td>
        <td><%= link_to 'Edit', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Destroy', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= paginate @unidades %>

app/views/unidades/edit.html.erb
<h1>Editing Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Show', @unidade %> |
<%= link_to 'Back', unidades_path %>

app/views/unidades/index.html.erb
<h1>Unidades <%= link_to '+', new_unidade_path %></h1>

<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>

<br>
<table border="1"><tr><td>
  <div>
    Pesquisa
    <%= f.text_field(:search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>

  <div>
    Ordenado por
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>

  <div>
    <%= link_to(
      'Limpar Filtros',
      reset_filterrific_url,
    ) %> &nbsp; <%= f.submit 'Filtrar' %>
  </div>

  <% end %>
  </td></tr></table>
  <br><br>

  <%= render(
  partial: 'unidades/list',
  locals: { unidades: @unidades }
) %>

app/views/unidades/new.html.erb
<h1>New Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Back', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @unidade.id %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @unidade.descricao %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @unidade.sigla %>
</p>

<p>
  <strong>Qtd dimensao:</strong>
  <%= @unidade.qtd_dimensao %>
</p>

<p>
  <strong>Monetaria:</strong>
  <%= @unidade.monetaria %>
</p>

<%= link_to 'Edit', edit_unidade_path(@unidade) %> |
<%= link_to 'Back', unidades_path %>