config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  resources :tipo_servicos
  resources :unidades
  resources :insumos
  resources :composicaos
  resources :servicos
  resources :obras
  resources :users
  resources :orcamentos

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get    'sign_out'  => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'


  root 'sessions#new'
end

app/models/insumo.rb
class Insumo < ActiveRecord::Base

  belongs_to :unidade
  enum tipo: { 
  	'Material': 0, 
  	'Mão de Obra': 1,
  }
  has_many :composicao
  has_many :servico, through: :composicao

  filterrific(
  default_filter_params: { sorted_by: 'descricao_desc' },
  available_filters: [
  	:sorted_by,
    :search_query,
    :with_tipo,
    :with_unidade_id
  ]
)
  scope :search_query, lambda { |query|
  	where("descricao LIKE ?", "%#{query}%")  
  }

  scope :with_tipo, lambda { |tipos|
    where(tipo: [*tipos])
  }

  scope :with_unidade_id, lambda { |unidade_ids|
    where(unidade_id: [*unidade_ids])
  }

  scope :sorted_by, lambda { |sort_option|
	  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
	  case sort_option.to_s
	  when /^descricao/
	    order("LOWER(insumos.descricao) #{ direction }")
	  when /^unidade/
	    order("LOWER(insumos.unidade) #{ direction }")
	  when /^tipo/
	    order("LOWER(insumos.tipo) #{ direction }")
	  else
	    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
	  end
  }

  def self.options_for_sorted_by
    [
      ['Tipo (a-z)', 'tipo_asc'],
      ['Tipo (z-a)', 'tipo_desc'],
      ['Descrição (a-z)', 'descricao_asc'],
      ['Descrição (z-a)', 'descricao_desc']
    ]
  end

  def self.options_for_select
    tipos.map do |tipo, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.tipos.#{tipo}"), tipo]
    end
  end
  
end

app/controllers/insumos_controller.rb
class InsumosController < ApplicationController
  before_action :set_insumo, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  
  # GET /insumos
  # GET /insumos.json
  def index
    @insumos = Insumo.all
    @unidade    = Unidade.all
    
    @filterrific = initialize_filterrific(
      Insumo,
      params[:filterrific]
    ) or return

    @filterrific.select_options = {
      sorted_by: Insumo.options_for_sorted_by,
      with_tipo: Insumo.options_for_select,
      with_unidade_id: Unidade.options_for_select
    }
    
    @insumos = @filterrific.find.page(params[:page]).per(20)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /insumos/1
  # GET /insumos/1.json
  def show
  end

  # GET /insumos/new
  def new
    @insumo = Insumo.new
  end

  # GET /insumos/1/edit
  def edit
    #@unidade = Unidade.find(params[:unidade_id])
  end

  # POST /insumos
  # POST /insumos.json
  def create
    @insumo = Insumo.new(insumo_params)

    respond_to do |format|
      if @insumo.save
        format.html { redirect_to @insumo, notice: 'Insumo criado com sucesso!' }
        format.json { render :show, status: :created, location: @insumo }
      else
        format.html { render :new }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insumos/1
  # PATCH/PUT /insumos/1.json
  def update
    respond_to do |format|
      if @insumo.update(insumo_params)
        format.html { redirect_to @insumo, notice: 'Insumo atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @insumo }
      else
        format.html { render :edit }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insumos/1
  # DELETE /insumos/1.json
  def destroy
    @insumo.destroy
    respond_to do |format|
      format.html { redirect_to insumos_url, notice: 'Insumo apagado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insumo
      @insumo = Insumo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insumo_params
      params.require(:insumo).permit(:descricao, :codigo_seinfra, :unidade_id, :tipo)
    end
  end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/views/insumos/_form.html.erb
<%= form_for(insumo) do |f| %>
  <% if insumo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insumo.errors.count, "error") %> prohibited this insumo from being saved:</h2>

      <ul>
      <% insumo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="field">
    <%= f.label :codigo_seinfra %>
    <%= f.text_field :codigo_seinfra %>
  </div>

  <div class="field">
    <%= f.label :unidade %>
    <%= f.select :unidade_id, options_for_select(Unidade.all.map{|u|[u.sigla, u.id]}, f.object.unidade_id) %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.select :tipo, Insumo.tipos.keys %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insumos/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info insumos %>
  </div>

  <table border="1">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Descricao</th>
      <th>Codigo seinfra</th>
      <th>Unidade</th>
      <th>Tipo de Insumo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insumos.each do |insumo| %>
      <tr>
        <td><%= insumo.id %></td>
        <td><%= insumo.descricao %></td>
        <td><%= insumo.codigo_seinfra %></td>
        <td><%= insumo.unidade.sigla %></td>
        <td><%= insumo.tipo %></td>
        <td><%= link_to 'Show', insumo %></td>
        <td><%= link_to 'Edit', edit_insumo_path(insumo) %></td>
        <td><%= link_to 'Destroy', insumo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= paginate @insumos %>

app/views/insumos/edit.html.erb
<h1>Editing Insumo</h1>

<%= render 'form', insumo: @insumo %>

<%= link_to 'Show', @insumo %> |
<%= link_to 'Back', insumos_path %>

app/views/insumos/index.html.erb
<h1>Insumos <%= link_to '+', new_insumo_path %></h1>

<br>
<table border="1"><tr><td>

<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
  <div>
    Pesquisa
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Tipo
    <%= f.select(
      :with_tipo,
      @filterrific.select_options[:with_tipo],
      { include_blank: '- Todos -' }
    ) %>
  </div>

  <div>
    Unidade
    <%= f.select(
      :with_unidade_id, 
      @filterrific.select_options[:with_unidade_id], 
      { include_blank: '- Todos -'})
    %>
  </div>
  <div>
    Ordenado por
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Limpar Filtros',
      reset_filterrific_url,
    ) %> &nbsp; <%= f.submit 'Filtrar' %>
  </div>
  
<% end %>
</td></tr></table>
<br><br>

<%= render(
  partial: 'insumos/list',
  locals: { insumos: @insumos }
) %>



<br>

app/views/insumos/new.html.erb
<h1>Cadastrar Insumo</h1>

<%= render 'form', insumo: @insumo %>

<%= link_to 'Back', insumos_path %>

app/views/insumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @insumo.id %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @insumo.descricao %>
</p>

<p>
  <strong>Codigo seinfra:</strong>
  <%= @insumo.codigo_seinfra %>
</p>

<p>
  <strong>Unidade:</strong>
  <%= @insumo.unidade.sigla %>
</p>

<p>
  <strong>Tipo de Insumo:</strong>
  <%= @insumo.tipo %>
</p>

<%= link_to 'Edit', edit_insumo_path(@insumo) %> |
<%= link_to 'Back', insumos_path %>