config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  resources :tipo_servicos
  resources :unidades
  resources :insumos
  resources :composicaos
  resources :servicos
  resources :obras
  resources :users
  resources :orcamentos

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get    'sign_out'  => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'


  root 'sessions#new'
end

app/models/obra.rb
class Obra < ActiveRecord::Base
	filterrific(
 		default_filter_params: { sorted_by: 'descricao_desc' },
  		available_filters: [
  			:sorted_by,
    		:search_query
  		]
	)

	scope :search_query, lambda { |query|
  		where("descricao LIKE ?", "%#{query}%")  
  	}

  	scope :sorted_by, lambda { |sort_option|
	  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
	  case sort_option.to_s
	  when /^descricao/
	    order("LOWER(obras.descricao) #{ direction }")
    when /^local/
      order("LOWER(obras.local) #{ direction }")
	  else
	    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
	  end
  	}

  	def self.options_for_sorted_by 
  		[
      	  ['Descrição (a-z)', 'descricao_asc'],
          ['Descrição (z-a)', 'descricao_desc'],
          ['Local (a-z)', 'local_asc'],
          ['Local (z-a)', 'local_desc']
    	]
  	end
	
	def self.options_for_select
  		order('LOWER(descricao)').map { |o| [o.descricao, o.id] }
  end
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  before_action :set_obra, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /obras
  # GET /obras.json
  def index
    @obras = Obra.all

    @filterrific = initialize_filterrific(
      Obra,
      params[:filterrific]
    ) or return

    @filterrific.select_options = {
      sorted_by: Obra.options_for_sorted_by
    }

    @obras = @filterrific.find.page(params[:page]).per(20)
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /obras/1
  # GET /obras/1.json
  def show
  end

  # GET /obras/new
  def new
    @obra = Obra.new
  end

  # GET /obras/1/edit
  def edit
  end

  # POST /obras
  # POST /obras.json
  def create
    @obra = Obra.new(obra_params)

    respond_to do |format|
      if @obra.save
        format.html { redirect_to @obra, notice: 'Obra foi criada com sucesso!' }
        format.json { render :show, status: :created, location: @obra }
      else
        format.html { render :new }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1
  # PATCH/PUT /obras/1.json
  def update
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to @obra, notice: 'A obra foi atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @obra }
      else
        format.html { render :edit }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras/1
  # DELETE /obras/1.json
  def destroy
    @obra.destroy
    respond_to do |format|
      format.html { redirect_to obras_url, notice: 'Obra removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obra
      @obra = Obra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obra_params
      params.require(:obra).permit(:descricao, :local)
    end
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/views/obras/_form.html.erb
<%= form_for(obra) do |f| %>
  <% if obra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obra.errors.count, "error") %> prohibited this obra from being saved:</h2>

      <ul>
      <% obra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="field">
    <%= f.label :local %>
    <%= f.text_field :local %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/obras/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info obras %>
  </div>

<table border="1">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Descricao</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obras.each do |obra| %>
      <tr>
        <td><%= obra.id %></td>
        <td><%= obra.descricao %></td>
        <td><%= obra.local %></td>
        <td><%= link_to 'Ver', obra %></td>
        <td><%= link_to 'Atualizar', edit_obra_path(obra) %></td>
        <td><%= link_to 'Apagar', obra, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<%= paginate @obras %>

app/views/obras/edit.html.erb
<h1>Editing Obra</h1>

<%= render 'form', obra: @obra %>

<%= link_to 'Show', @obra %> |
<%= link_to 'Back', obras_path %>

app/views/obras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Obras <%= link_to '+', new_obra_path %></h1>

<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>

<br>
<table border="1"><tr><td>
  <div>
    Pesquisa
    <%= f.text_field(:search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>

  <div>
    Ordenado por
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>

  <div>
    <%= link_to(
      'Limpar Filtros',
      reset_filterrific_url,
    ) %> &nbsp; <%= f.submit 'Filtrar' %>
  </div>

  <% end %>
  </td></tr></table>
  <br><br>

  <%= render(
  partial: 'obras/list',
  locals: { obras: @obras }
) %>

app/views/obras/new.html.erb
<h1>Cadastrar Obra</h1>

<%= render 'form', obra: @obra %>

<%= link_to 'Voltar', obras_path %>

app/views/obras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @obra.descricao %>
</p>

<p>
  <strong>Local:</strong>
  <%= @obra.local %>
</p>

<%= link_to 'Edit', edit_obra_path(@obra) %> |
<%= link_to 'Back', obras_path %>