config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  resources :tipo_servicos
  resources :unidades
  resources :insumos
  resources :composicaos
  resources :servicos
  resources :obras
  resources :users
  resources :orcamentos

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  get    'sign_out'  => 'sessions#destroy'
  delete 'sign_out'  => 'sessions#destroy'


  root 'sessions#new'
end

app/views/layouts/_header.html.erb
<header>
    <div>
      <nav>
        <ul class="menu">
          <% if logged_in? %>
            <li><a href="#">Minha Conta</a><ul>
              <li><%= link_to "Usuários", users_path %></li>
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
              <li>
                  <%= link_to "Sair", sign_out_path, method: "delete" %>
              </li>
             </ul></li>

            <!-- Tabelas base-->
            <li><a href="#">Tabelas de Apoio</a><ul>
              <li>
                  <%= link_to "Unidades", unidades_path %>
              </li>
              
              <li><%= link_to "TipoServicos", tipo_servicos_path %>
              </li>
              
              <li>
                <%= link_to "Servicos", servicos_path %>
              </li>
              
              <li>
                <%= link_to "Insumos", insumos_path %>
              </li>

              <li>
                <%= link_to "Composições", composicaos_path %>
              </li>
            </ul></li>

            <!-- Orçamentos -->
            <li><a href="#">Orçamentos</a><ul>
              <li>
                  <%= link_to "Cadastrar Obras", obras_path %>
              </li>

              <li>
                  <%= link_to "Gerar Orçamentos", orcamentos_path %>
              </li>
            </ul></li>
          <% end %>
        </ul>
      </nav>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orc</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Arquivo css externo -->
    <%= stylesheet_link_tag    'menu', media: 'all', 'data-turbolinks-track' => true %>
 </head>

  <body>
    <%= render 'layouts/header' %>
      <br><br>
      <p></p>
    <%= yield %>
    <footer>
      <sub>
        EngOrc | Sistema de Orçamento para Engenharia
      </sub>
    </footer>
  </body>
</html>